---

- name: Pull NGINX docker image (version {{nginx_version}})
  docker_image:
    name: nginx:{{nginx_version}}
    source: pull

# TODO: This should probably be moved to a different role
# - name: Create docker network ({{ network_name }})
#   docker_network:
#     name: "{{ network_name }}"
#     driver: bridge

# Copy files to NGINX volumes

- name: Ensure NGINX directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - /var/www
    - /var/nginx/conf.d

- name: Copy files to the server
  copy:
    src: "{{ item.src }}" 
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - src: test.html
      dest: /var/www/test.html
    - src: default.conf
      dest: /var/nginx/conf.d/default.conf

- name: Create conf file for server
  template:
    src: server.conf.j2
    dest: /var/nginx/conf.d/server.conf

# Create/Start the container
  
- name: Run NGINX container
  docker_container:
    name: web-gateway
    image: nginx:{{nginx_version}}
    state: started
    networks:
      - name: "{{ network_name }}"
    ports:
      - "80:80"
    volumes:      
      - "/var/www:/usr/share/nginx/html:ro"
      - "/var/nginx/conf.d:/etc/nginx/conf.d:ro"
