---

- name: Deploy Web App
  hosts: all
  roles:
    - docker-setup
    - node-exporter
    - test-file-server
    - adminer
    - nginx
  tasks:
    - name: Flush handlers
      meta: flush_handlers
  vars:
    - network_name: web-app-network
