---

- hosts: all
  gather_facts: yes

  pre_tasks:
    - name: Set application network name
      set_fact:
        app_network: "{{ app_name }}-network"

  roles:
    - role: hello-world
      
  vars:
    - doc_contents: "This is the HELLO WORLD test #2"
