---
          
- name: System details
  debug:
    msg: "{{ ansible_distribution }} {{ ansible_distribution_version }} ({{ ansible_architecture }})"
  
- name: Test multi-line output
  become: yes
  shell: "ls -l ; whoami"
  register: ls_result

- name: Print output
  debug:
    var: ls_result.stdout_lines

- name: Print debug message
  debug:
    msg: "Hello, World!"

- name: Print value of app_name
  debug:
    var: app_name

- name: Print value of app_domains
  debug:
    msg: "{{ app_domains|join(', ') }}"

- name: Print value of hello_world.test_var
  debug:
    msg: "{{ hello_world.test_var }}"

- name: Print value of hello_world.test_arr
  debug:
    msg: "{{ hello_world.test_arr|join('-') }}"

- name: "Create file in {{ ansible_user }}'s home folder"
  template:
    src: hello_world.txt.j2
    dest: ~/hello_world.txt
