---

## Display OS version

- name: System details
  debug:
    msg: "{{ ansible_distribution }} {{ ansible_distribution_version }} ({{ ansible_architecture }})"

## Get list of networks that we are interested in

- name: Get Docker network names ending with '-network'
  become: yes
  shell: "docker network ls --format '{{ '{{' }}.Name{{ '}}' }}'"
  register: all_docker_networks
  changed_when: false

- name: Filter networks ending with '-network'
  set_fact:
    gateway_networks: "{{ all_docker_networks.stdout_lines | select('match', '.*-network$') | list }}"

- name: Print the filtered Docker network names
  debug:
    msg: "{{ gateway_networks }}"

## Print variables

- name: Set the variables list
  set_fact:
    variables_list:
      - "app_name: {{ app_name }}"
      - "app_network: {{ app_network }}"
      - "app_domains: {{ app_domains|join(', ') }}"
      - "hello_world.test_var: {{ hello_world.test_var }}"
      - "hello_world.test_arr: {{ hello_world.test_arr|join('-') }}"
      - "ansible_user: {{ ansible_user }}"

- name: Print the variables
  debug:
    msg: "{{ variables_list | list }}"

## Original Hello World tests

- name: Print debug message
  debug:
    msg: "Hello, World!"

- name: Create file in user's home folder
  template:
    src: hello_world.txt.j2
    dest: ~/hello_world.txt

## Test multi lline output

- name: Test multi-line output
  shell: "whoami ; date"
  register: result
  changed_when: false

- name: Print output
  debug:
    var: result.stdout_lines
