---
          
- name: System details
  debug:
    msg: "{{ ansible_distribution }} {{ ansible_distribution_version }} ({{ ansible_architecture }})"

- name: Print debug message
  debug:
    msg: "Hello, World!"

- name: Print value of app_name
  debug:
    var: app_name

- name: Print value of app_domains
  debug:
    msg: "{{ app_domains|join(', ') }}"

- name: Print value of my_service.db_user
  debug:
    var: my_service.db_user

- name: Print value of my_service.db_user
  debug:
    msg: "{{ my_defaults.test_var1 }}"

- name: Print value of app_domains
  debug:
    msg: "{{ my_defaults.test_arr1|join('-') }}"

- name: Create file in user's home folder
  template:
    src: hello_world.txt.j2
    dest: ~/hello_world.txt
