---

- name: Run docker RabbitMQ container
  docker_container:
    name: "{{ app_name }}-rabbitmq"
    image: rabbitmq:3.13.2-management-alpine
    pull: yes
    state: started
    restart_policy: unless-stopped
    env:
      RABBITMQ_DEFAULT_USER: "{{ admin.username }}"
      RABBITMQ_DEFAULT_PASS: "{{ admin.password }}"
    expose:
      - 15672
    ports:
      - "5672:5672"
    networks:
      - name: "{{ network_name }}"

- name: Create log queue and set TTL policy
  community.docker.docker_container_exec:
    container: "{{ app_name }}-rabbitmq"
    command: rabbitmqadmin -u "{{ admin.username }}" -p "{{ admin.password }}" declare queue name=log-queue durable=true arguments='{"x-message-ttl":3600000}'
        
# Copy NGINX location file to server

- name: Set the config directory path
  set_fact:
    config_directory: "/etc/{{ nginx_container }}/servers/{{ app_name }}/locations"

- name: Make sure directory exists
  ansible.builtin.file:
    path: "{{ config_directory }}"
    state: directory
    
- name: Copy conf file for server
  template:
    src: nginx-location.conf.j2
    dest: "{{ config_directory }}/{{ app_name }}-rabbitmq.conf"
  notify:
    - Restart NGINX
