---

# - name: Set container name
#   vars:
#     container_name: "{{ app_name }}-rabbitmq"
    
- name: Run docker RabbitMQ container
  docker_container:
    name: "{{ app_name }}-rabbitmq"
    image: rabbitmq:3.13.2-management-alpine
    pull: yes
    state: started
    restart_policy: unless-stopped
    env:
      RABBITMQ_DEFAULT_USER: "{{ admin.username }}"
      RABBITMQ_DEFAULT_PASS: "{{ admin.password }}"
    expose:
      - 15672
    ports:
      - "5672:5672"
    networks:
      - name: "{{ network_name }}"

# Copy NGINX location file to server

- name: Make sure directory exists
  ansible.builtin.file:
    path: "/var/nginx/{{ app_name }}/locations"
    state: directory
    
- name: Copy conf file for server
  template:
    src: nginx-location.conf.j2
    dest: "/var/nginx/{{ app_name }}/locations/{{ app_name }}-rabbitmq.conf"
  notify:
    - Restart NGINX
