---

- name: Pull Adminer docker image
  docker_image:
    name: adminer:4.8.1-standalone
    source: pull

- name: Run Adminer container
  docker_container:
    name: "{{ container_name }}"
    image: adminer:4.8.1-standalone
    state: started
    networks:
      - name: "{{ network_name }}"
    expose:
      - "8080"
    env:
      ADMINER_DESIGN: flat

# Copy NGINX location file to server

- name: Set the config directory path
  set_fact:
    config_directory: "/etc/{{ nginx_container }}/servers/{{ app_name }}/locations"

- name: Make sure directory exists
  ansible.builtin.file:
    path: "{{ config_directory }}"
    state: directory
    
- name: Copy conf file for server
  template:
    src: nginx-location.conf.j2
    dest: "{{ config_directory }}/{{ container_name }}.conf"
  notify:
    - Restart NGINX
