---
# Test for uploading file and copying into NGINX container
- name: File upload test
  hosts: all

  tasks:
    - name: Pull the latest Alpine image
      docker_image:
        name: alpine
        source: pull

    - name: Create a temporary container with RW access to the Docker volume
      docker_container:
        name: temp-file-manager
        image: alpine
        command: sleep 3600
        volumes:
          - "webx-gateway-data:/data:rw"
        state: started
        
    - name: Create a temporary file
      tempfile:
        state: file
        suffix: .html
      register: temp_file

    - name: Copy local file to the temporary path
      copy:
        src: ../data/test.html
        dest: "{{ temp_file.path }}"
        owner: root
        group: root
        mode: '0644'
        
    - name: Copy temporary file to Docker container
      command: docker cp "{{ temp_file.path }}" temp-file-manager:/data/test.html

    - name: Remove temporary file
      file:
        path: "{{ temp_file.path }}"
        state: absent
        
    - name: Remove the temporary container
      docker_container:
        name: temp-file-manager
        state: absent
