---                                                                                                                                                                                                                                           
# This playbook prints a simple debug message
- name: Echo
  hosts: all
  
  tasks:
    - name: Print debug message
      debug:
        msg: Hello, world!

    - name: Create file in user's home folder
      ansible.builtin.file:
        path: ~/hello_world.txt
        state: touch
      tags:
        - create_file
