---
- name: Install and run NGINX
  hosts: all

  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install docker engine
      apt:
        name: docker.io
        state: present

    - name: Install docker compose
      apt:
        name: docker-compose
        state: present

    - name: Start docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Pull NGINX docker image
      docker_image:
        name: nginx:1.25.5
        source: pull

    - name: Create docker volume
      docker_volume:
        name: webx-gateway-data
        driver: local

    - name: Run NGINX container
      docker_container:
        name: webx-gateway
        image: nginx:1.25.5
        state: started
        ports:
          - "80:80"
        volumes:
          - "webx-gateway-data:/usr/share/nginx/html:ro"
