---
fileservice_db_root_password: password
fileservice_db_user: appuser
fileservice_db_password: password
fileservice_db_database: files_db
fileservice_db_volume: volume-fileservice-db
fileservice_api_volume: volume-fileservice-api
